In [41]:
import numpy as np

x = np.arange(10)
print(x)

x = x.reshape(2,5)
print(x)
y = np.arange(5)
x = np.append(x,y)
print(y)
#
x = np.append(x,y)
#x = np.reshape(5,4)
print(x)
x.reshape(5,4)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4]
[0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 0 1 2 3 4]


array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [8, 9, 0, 1],
       [2, 3, 4, 0],
       [1, 2, 3, 4]])

In [72]:
import numpy as np
from PIL import Image
import os
from pathlib import Path

#import basicoperations
from basicoperations import *
from basicoperations import requantize

# Loadig a grayscale image

subfolder = "Image dataset"
folder_path = os.getcwd()
# Construct the full path
subfolder_path = os.path.join(folder_path, subfolder)

print('Address ',subfolder_path)

#auxiliary variables to select the image
choose = 2
i=1

for fileName in os.listdir(subfolder_path):
    if  (fileName.endswith('.png') or fileName.endswith('.jpg') or fileName.endswith('.bmp')) and (not fileName.startswith('resized')):
        if (i<choose):
            print(f'Selected Image: {fileName}')
            image_path = os.path.join(subfolder_path, fileName)
            image = Image.open(image_path)
            image = image.convert("L")
            break
    i+=1

# Convert image to a NumPy array
image_array = np.array(image)


# Requantize to 4 bits = 16 levels (e.g., 0, 16, 32, 48, 64, 80, 96, 112, 128, 144, 160, 176, 192, 208, 224, 240 )
# Requantize to 2 bits = 4 levels (e.g., 0, 64, 128, 192)
# Requantize to 1 bit = 2 levels (e.g. 0, 256)
num_levels = 8
requantized_image = requantize.requantize_image(image_array, num_levels)

# Construct histogram
unique_values, counts = np.unique(requantized_image, return_counts=True)
pmf = counts/(sum(counts))
xpmf = unique_values*pmf

# Calculating metrics
meanValue,expectedValue, modeValue, medianValue = features.calculateValues(unique_values,pmf,xpmf)


secondOrderMoment = moments.second_order_moment(unique_values,pmf)
thirdOrderMoment = moments.third_order_moment(unique_values,pmf)
centralSecond = moments.central_second_order_moment(unique_values,pmf,expectedValue)
centralThird = moments.central_third_order_moment(unique_values,pmf,expectedValue)
skew = kurtosis_skewness.skewness(unique_values,pmf,meanValue)
kurt = kurtosis_skewness.kurtosis(unique_values,pmf,meanValue)
E = entropy.evaluateEntropy(pmf) 



print("Media:", meanValue,"\nExpectancia:",expectedValue,"\nModa:",modeValue,"\nMediana:",medianValue)
print(f'Momento 2: {secondOrderMoment},\n Segundo Central: {centralSecond}\nMomento 3: {thirdOrderMoment},\nTerceiro Central: {centralThird},\nSkewness: {skew},\nKurtosis: {kurt}')

# Plot the histogram
#plot.plots(unique_values,counts)

Address  D:\stochastics\Image dataset
Media: 112.0 
Expectancia: 103.19146411588065 
Moda: 0 
Mediana: 96
Momento 2: 16102.458648606713,
 Segundo Central: 681.7475477784535
Momento 3: 2730581.6269658,
Terceiro Central: -56663.0986520703,
Skewness: -11.080911144924707,
Kurtosis: 112.87297673584247


In [6]:
#for fileName in (os.path.join(folder_path, subfolder).rglob("*")):
from pathlib import Path
cwd = Path.cwd()
target_dir = cwd / "Image dataset"
for fileName in (target_dir.rglob("*")):
    fileName = str(fileName)
    if  (fileName.endswith('.png') or fileName.endswith('.jpg') or fileName.endswith('.bmp')) and (not fileName.startswith('resized')):
        #if (i==choose):
   #     print(f'Selected Image: {fileName}')
        #image_path = os.path.join(subfolder_path, fileName)
        image = Image.open(fileName)
        image = image.convert("L")
    i = 1
# for fileName in os.listdir(target_dir):
#     if  (fileName.endswith('.png') or fileName.endswith('.jpg') or fileName.endswith('.bmp')) and (not fileName.startswith('resized')):
#         #if (i==choose):
#         print(f'Selected Image: {fileName}')
#         image_path = os.path.join(subfolder_path, fileName)
#         image = Image.open(image_path)
#         image = image.convert("L")
#         #break
#     i+=1
    

In [8]:
import numpy as np
from PIL import Image
import os
from pathlib import Path

#import basicoperations
#from basicoperations import *
from basicoperations import requantize
from modules.verify_file import verifyFile

# Loadig a grayscale image
#auxiliary variables to select the image
choose = 2
i=1

#from pathlib import Path
cwd = Path.cwd()
target_dir = cwd / "Image dataset"
for fileName in (target_dir.rglob("*")):
    fileName = str(fileName)
    if  (fileName.endswith('.png') or fileName.endswith('.jpg') or fileName.endswith('.bmp')):
        #if (i==choose):
        print(f'Selected Image: {fileName}')
        #image_path = os.path.join(subfolder_path, fileName)
        image = Image.open(fileName)
        image = image.convert("L")
        image_array = np.array(image)
        num_levels = 8
        requantized_image = requantize.requantize_image(image_array, num_levels)
        

# Construct histogram
        unique_values, counts = np.unique(requantized_image, return_counts=True)
        pmf = counts/(sum(counts))
        xpmf = unique_values*pmf
        if fileName.__contains__('Alzheimer'):
            number =0
        elif fileName.__contains__('COVID'):
            number =1
        elif fileName.__contains__('Brazilian_Seeds'):
            number =2
        elif fileName.__contains__('Brazilian_Leaves'):
            number =3
        else:
            number =4
        verifyFile(pmf, number)
# Calculating metrics
    #     meanValue,expectedValue, modeValue, medianValue = features.calculateValues(unique_values,pmf,xpmf)


    #     secondOrderMoment = moments.second_order_moment(unique_values,pmf)
    #     thirdOrderMoment = moments.third_order_moment(unique_values,pmf)
    #     centralSecond = moments.central_second_order_moment(unique_values,pmf,expectedValue)
    #     centralThird = moments.central_third_order_moment(unique_values,pmf,expectedValue)
    #     skew = kurtosis_skewness.skewness(unique_values,pmf,meanValue)
    #     kurt = kurtosis_skewness.kurtosis(unique_values,pmf,meanValue)
    #     E = entropy.evaluateEntropy(pmf) 
    # i+=1

# Convert image to a NumPy array



# Requantize to 4 bits = 16 levels (e.g., 0, 16, 32, 48, 64, 80, 96, 112, 128, 144, 160, 176, 192, 208, 224, 240 )
# Requantize to 2 bits = 4 levels (e.g., 0, 64, 128, 192)
# Requantize to 1 bit = 2 levels (e.g. 0, 256)




print("Media:", meanValue,"\nExpectancia:",expectedValue,"\nModa:",modeValue,"\nMediana:",medianValue)
print(f'Momento 2: {secondOrderMoment},\n Segundo Central: {centralSecond}\nMomento 3: {thirdOrderMoment},\nTerceiro Central: {centralThird},\nSkewness: {skew},\nKurtosis: {kurt}')

# Plot the histogram
#plot.plots(unique_values,counts)

Selected Image: D:\stochastics\Image dataset\Alzheimer\1.jpg
Line already exists in files-generated.csv
Selected Image: D:\stochastics\Image dataset\Alzheimer\10.jpg
Line already exists in files-generated.csv
Selected Image: D:\stochastics\Image dataset\Alzheimer\11.jpg
Line already exists in files-generated.csv
Selected Image: D:\stochastics\Image dataset\Alzheimer\12.jpg
Line already exists in files-generated.csv
Selected Image: D:\stochastics\Image dataset\Alzheimer\13.jpg
Line already exists in files-generated.csv
Selected Image: D:\stochastics\Image dataset\Alzheimer\14.jpg
Line already exists in files-generated.csv
Selected Image: D:\stochastics\Image dataset\Alzheimer\15.jpg
Line already exists in files-generated.csv
Selected Image: D:\stochastics\Image dataset\Alzheimer\16.jpg
Line already exists in files-generated.csv
Selected Image: D:\stochastics\Image dataset\Alzheimer\17.jpg
Line already exists in files-generated.csv
Selected Image: D:\stochastics\Image dataset\Alzheimer\1

IndexError: index 7 is out of bounds for axis 0 with size 7